### ISSUE TITLE
sites down 4/24/2020

### ISSUE THREAD

**Issue by apena813** [ModerateContent/image-moderation#2]
i noticed the api is no longer working and the site is down as well. Is there any particular reason for this and will this occur frequently?

I've seen this happen a while ago and am curious if this will become a regular event.

**Comment by ModerateContent** [comment]
We are experiencing a DDoS denial of service attack. Please consider using our alternative API endpoint https://api.moderatecontent.com/moderate/

**Comment by brandon-origin** [comment]
I'm sorry to hear that and thanks for the response.

I looked into the npm module index.js file, where the .evaluate and .is_adult are defined. I pasted the image of where the urls are defined, would that be the best file to change to the new url you sent? 

![image](https://user-images.githubusercontent.com/63412882/79383757-bbdb6a00-7f33-11ea-9721-c0015fe82673.png)

**Comment by apena813** [comment]
I'm sorry to hear that and thanks for the timely response.

I opened the npm node_module where the .evaluate and .is_adult functions are defined. Is this the best location to update the url you provided? I have attached an image with the code location:

![image](https://user-images.githubusercontent.com/59887185/79384197-6fdcf500-7f34-11ea-8665-941cd75c17d0.png)

**Comment by apena813** [comment]
![image](https://user-images.githubusercontent.com/59887185/79384243-7d927a80-7f34-11ea-9fba-ac454d4e09ea.png)
